/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.zoopolis.view;

import com.zoopolis.model.Animal;
import com.zoopolis.model.AnimalDomestico;
import com.zoopolis.model.AnimalSalvaje;
import com.zoopolis.model.Zoopolis;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Joseph Roldan, Carlos Castaño, Osvairo Moreno
 */
public class Animales extends javax.swing.JFrame {

    /**
     * Creates new form Animales
     */
    
    DefaultTableModel t = new DefaultTableModel();
    
    public Animales() {
        initComponents();
        btnAnimal.setForeground(new java.awt.Color(1, 196, 76));
        btnAnimal.setFont(new java.awt.Font("Arial", 1, 25));
        llenarTabla();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnimales = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnAnimal = new javax.swing.JButton();
        btnRegistroAnimal = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnBalance = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Logo.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 300, 90));

        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tblAnimales.setBackground(new java.awt.Color(227, 251, 245));
        tblAnimales.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblAnimales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Especie", "Sexo", "Edad", "Raza", "Color", "Peligrosidad", "Habitat", "Descripcion"
            }
        ));
        tblAnimales.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblAnimales.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        tblAnimales.setRowHeight(50);
        tblAnimales.setRowSelectionAllowed(false);
        tblAnimales.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tblAnimales.setShowGrid(true);
        jScrollPane1.setViewportView(tblAnimales);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 900, 370));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 196, 76));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de Animales");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 900, 40));

        btnExit.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Exit.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setDefaultCapable(false);
        btnExit.setFocusPainted(false);
        btnExit.setFocusable(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 50, 50, 50));

        btnAnimal.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnAnimal.setText("Animales");
        btnAnimal.setBorder(null);
        btnAnimal.setBorderPainted(false);
        btnAnimal.setContentAreaFilled(false);
        btnAnimal.setDefaultCapable(false);
        btnAnimal.setFocusPainted(false);
        btnAnimal.setFocusable(false);
        btnAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimalActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 130, 50));

        btnRegistroAnimal.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnRegistroAnimal.setText("Registro Animal");
        btnRegistroAnimal.setBorder(null);
        btnRegistroAnimal.setBorderPainted(false);
        btnRegistroAnimal.setContentAreaFilled(false);
        btnRegistroAnimal.setDefaultCapable(false);
        btnRegistroAnimal.setFocusPainted(false);
        btnRegistroAnimal.setFocusable(false);
        btnRegistroAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAnimalActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistroAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 210, 50));

        btnInicio.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setBorder(null);
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setDefaultCapable(false);
        btnInicio.setFocusPainted(false);
        btnInicio.setFocusable(false);
        jPanel1.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 100, 50));

        btnBalance.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnBalance.setText("Balance");
        btnBalance.setBorder(null);
        btnBalance.setBorderPainted(false);
        btnBalance.setContentAreaFilled(false);
        btnBalance.setDefaultCapable(false);
        btnBalance.setFocusPainted(false);
        btnBalance.setFocusable(false);
        btnBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceActionPerformed(evt);
            }
        });
        jPanel1.add(btnBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        IndexAdmin.exit();
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimalActionPerformed
        IndexAdmin.irAnimales();
        dispose();
    }//GEN-LAST:event_btnAnimalActionPerformed

    private void btnRegistroAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAnimalActionPerformed
        IndexAdmin.irRegsitroAnimal();
        dispose();
    }//GEN-LAST:event_btnRegistroAnimalActionPerformed

    private void btnBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceActionPerformed
        IndexAdmin.irBalance();
        dispose();
    }//GEN-LAST:event_btnBalanceActionPerformed

    private void llenarTabla(){
        String[] columnas = {"Especie", "Sexo", "Edad", "Raza", "Color", "Peligrosidad", "Hábitad", "Descripción"};
        t.setColumnIdentifiers(columnas);
        for (AnimalDomestico a : Zoopolis.animalesDomestico) {
            t.addRow(a.getVector());
        }
        for (AnimalSalvaje a : Zoopolis.animalesSalvaje) {
            t.addRow(a.getVector());
        }
        tblAnimales.setModel(t);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Animales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Animales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Animales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Animales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Animales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnimal;
    private javax.swing.JButton btnBalance;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegistroAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTable tblAnimales;
    // End of variables declaration//GEN-END:variables
}
