/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.zoopolis.view;

/**
 *
 * @author Joseph Roldan, Carlos Castaño, Osvairo Moreno
 */
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactoryImp;
import com.zoopolis.model.AnimalDomestico;
import com.zoopolis.model.AnimalSalvaje;
import com.zoopolis.model.Usuario;
import com.zoopolis.model.Zoopolis;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Josinwua
 */
public class Balance extends javax.swing.JFrame {

    /**
     * Creates new form Balance
     */
    private int[] cantidad = new int[6];
    private double[] acum = new double[18];
        DefaultTableModel t = new DefaultTableModel();

    public Balance() {
        initComponents();
        btnBalance.setForeground(new java.awt.Color(1, 196, 76));
        btnBalance.setFont(new java.awt.Font("Arial", 1, 25));
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnInicio1 = new javax.swing.JButton();
        btnRegistroAnimal = new javax.swing.JButton();
        btnAnimal = new javax.swing.JButton();
        btnBalance = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Logo.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 300, 90));

        btnImprimir.setBackground(new java.awt.Color(1, 196, 76));
        btnImprimir.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnImprimir.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimir.setText("IMPRIMIR");
        btnImprimir.setBorder(null);
        btnImprimir.setContentAreaFilled(false);
        btnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprimir.setFocusPainted(false);
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir.setOpaque(true);
        btnImprimir.setRequestFocusEnabled(false);
        btnImprimir.setVerifyInputWhenFocusTarget(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, 180, 50));

        jScrollPane1.setBorder(null);
        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tblRegistro.setBackground(new java.awt.Color(227, 251, 245));
        tblRegistro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblRegistro.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        tblRegistro.setRowHeight(50);
        tblRegistro.setRowMargin(5);
        tblRegistro.setRowSelectionAllowed(false);
        tblRegistro.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tblRegistro.setShowGrid(true);
        jScrollPane1.setViewportView(tblRegistro);
        if (tblRegistro.getColumnModel().getColumnCount() > 0) {
            tblRegistro.getColumnModel().getColumn(2).setResizable(false);
            tblRegistro.getColumnModel().getColumn(3).setResizable(false);
            tblRegistro.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 900, 370));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 196, 76));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de ventas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 900, 40));

        btnExit.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Exit.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setDefaultCapable(false);
        btnExit.setFocusPainted(false);
        btnExit.setFocusable(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 50, 50, 50));

        btnInicio1.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnInicio1.setText("Inicio");
        btnInicio1.setBorder(null);
        btnInicio1.setBorderPainted(false);
        btnInicio1.setContentAreaFilled(false);
        btnInicio1.setDefaultCapable(false);
        btnInicio1.setFocusPainted(false);
        btnInicio1.setFocusable(false);
        btnInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicio1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 100, 50));

        btnRegistroAnimal.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnRegistroAnimal.setText("Registro Animal");
        btnRegistroAnimal.setBorder(null);
        btnRegistroAnimal.setBorderPainted(false);
        btnRegistroAnimal.setContentAreaFilled(false);
        btnRegistroAnimal.setDefaultCapable(false);
        btnRegistroAnimal.setFocusPainted(false);
        btnRegistroAnimal.setFocusable(false);
        btnRegistroAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAnimalActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistroAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 210, 50));

        btnAnimal.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnAnimal.setText("Animales");
        btnAnimal.setBorder(null);
        btnAnimal.setBorderPainted(false);
        btnAnimal.setContentAreaFilled(false);
        btnAnimal.setDefaultCapable(false);
        btnAnimal.setFocusPainted(false);
        btnAnimal.setFocusable(false);
        btnAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimalActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 130, 50));

        btnBalance.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnBalance.setText("Balance");
        btnBalance.setBorder(null);
        btnBalance.setBorderPainted(false);
        btnBalance.setContentAreaFilled(false);
        btnBalance.setDefaultCapable(false);
        btnBalance.setFocusPainted(false);
        btnBalance.setFocusable(false);
        btnBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceActionPerformed(evt);
            }
        });
        jPanel1.add(btnBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed

        try {
            String ruta = System.getProperty("user.home");
            Document document = new Document();

            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("src/main/resources/reporte/ReporteVentas.pdf"));

            // Encabezado con imagen
            Image header = Image.getInstance("src/main/resources/assets/header.png");
            header.scaleToFit(600, 1000);
            header.setAlignment(Chunk.ALIGN_CENTER);
            PdfPTable table = new PdfPTable(7);
            
            
            
            table.setWidthPercentage(100);
            PdfPCell cell1 = new PdfPCell(new Phrase("Descuentos"));
            cell1.setColspan(2); // establecer que la celda ocupa dos columnas
            cell1.setHorizontalAlignment(Element.ALIGN_CENTER);
            Paragraph saltolinea = new Paragraph("\n\n\n");
            Paragraph paragraph = new Paragraph("Reporte ventas");
            
            
//            FontFactory ff = new FontFactory();
            // Contenido

            document.open();
            document.add(header);
            document.add(saltolinea);
            document.add(paragraph);
            document.add(saltolinea);

            table.addCell("Plan");
            table.addCell("Valor");
            table.addCell("Cantidad");
            table.addCell("Valor venta");
            table.addCell(cell1);
            table.addCell("Total");

            ArrayList<ArrayList> cv = Zoopolis.calcularVentas();

            for (ArrayList fila : cv) {
                
                    table.addCell((String) fila.get(0));
                    table.addCell((String) fila.get(1));
                    table.addCell((String) fila.get(2));
                    table.addCell((String) fila.get(3));
                    table.addCell((String) fila.get(4));
                    table.addCell((String) fila.get(5));
                    table.addCell((String) fila.get(6));
                
            }

            table.setHorizontalAlignment(Element.ALIGN_CENTER);
            document.add(table);
            // Pie de página con imagen                resources
            Image footerImage = Image.getInstance("src/main/resources/assets/footer.png");
            footerImage.scaleToFit(600, 1000);
            footerImage.setAlignment(Image.ALIGN_CENTER);
            Footer event2 = new Footer(footerImage);
            writer.setPageEvent(event2);

            document.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Balance.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BadElementException ex) {
            Logger.getLogger(Balance.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Balance.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(Balance.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "Reporte Generado");


    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        IndexAdmin.exit();
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicio1ActionPerformed
        IndexAdmin.irInicio();
        dispose();
    }//GEN-LAST:event_btnInicio1ActionPerformed

    private void btnRegistroAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAnimalActionPerformed
       IndexAdmin.irRegsitroAnimal();
        dispose();
    }//GEN-LAST:event_btnRegistroAnimalActionPerformed

    private void btnAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimalActionPerformed
        IndexAdmin.irAnimales();
        dispose();
    }//GEN-LAST:event_btnAnimalActionPerformed

    private void btnBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceActionPerformed

    }//GEN-LAST:event_btnBalanceActionPerformed

    private void llenarTabla(){
        String[] columnas = {"Plan", "Valor", "Cantidad", "Valor Venta", "Porcentaje", "Descuento", "Total"};
        t.setColumnIdentifiers(columnas);
        for (ArrayList fila: Zoopolis.calcularVentas()) {
            t.addRow(fila.toArray());
        }
        tblRegistro.setModel(t);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Balance().setVisible(true);
            }
        });
    }

    private static class Footer extends PdfPageEventHelper {

        private final Image footerImage;

        public Footer(Image footerImage) {
            this.footerImage = footerImage;
        }

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            PdfContentByte canvas = writer.getDirectContent();
            float x = (PageSize.A4.getWidth() - footerImage.getScaledWidth()) / 2;
            float y = -10;
            try {
                canvas.addImage(footerImage, footerImage.getScaledWidth(), 0, 0, footerImage.getScaledHeight(), x, y);
            } catch (DocumentException ex) {
                Logger.getLogger(Balance.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnimal;
    private javax.swing.JButton btnBalance;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnInicio1;
    private javax.swing.JButton btnRegistroAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTable tblRegistro;
    // End of variables declaration//GEN-END:variables
}
