/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.zoopolis.view;

import com.zoopolis.model.Ticket;
import com.zoopolis.model.Venta;
import com.zoopolis.model.Zoopolis;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Josinwua
 */
public class Compra extends javax.swing.JDialog {

    /**
     * Creates new form Compras
     */
    private Venta ventaLocal;

    public Compra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        lblTitulo.setText(Tickets.temporal.get(0).toString());
        lblCantidad.setText(Tickets.temporal.get(1).toString());
        lblValorUnidad.setText(Tickets.temporal.get(2).toString());
        Subtotal.setText(Tickets.temporal.get(3).toString());
        lblTotal.setText(Tickets.temporal.get(3).toString());
        txADescripcion.setText(Tickets.temporal.get(4).toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmCrearCuenta = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        btnCrearCuenta = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnInicioDeSesion = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        lblLogo1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblValorUnidad = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txADescripcion = new javax.swing.JTextArea();
        Subtotal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrearCuenta.setBackground(new java.awt.Color(1, 196, 76));
        btnCrearCuenta.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCuenta.setText("CREAR CUENTA");
        btnCrearCuenta.setBorder(null);
        btnCrearCuenta.setContentAreaFilled(false);
        btnCrearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearCuenta.setFocusPainted(false);
        btnCrearCuenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCrearCuenta.setOpaque(true);
        btnCrearCuenta.setRequestFocusEnabled(false);
        btnCrearCuenta.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 180, 50));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("REGISTRO");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 300, -1));

        btnInicioDeSesion.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnInicioDeSesion.setForeground(new java.awt.Color(153, 153, 153));
        btnInicioDeSesion.setText("Iniciar Sesion");
        btnInicioDeSesion.setBorder(null);
        btnInicioDeSesion.setBorderPainted(false);
        btnInicioDeSesion.setContentAreaFilled(false);
        btnInicioDeSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicioDeSesion.setDefaultCapable(false);
        btnInicioDeSesion.setFocusPainted(false);
        btnInicioDeSesion.setFocusable(false);
        btnInicioDeSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInicioDeSesion.setRequestFocusEnabled(false);
        btnInicioDeSesion.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnInicioDeSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 180, 50));

        jTextField1.setBackground(new java.awt.Color(227, 251, 230));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 196, 76), 2));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 340, 60));

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Logo.png"))); // NOI18N
        jPanel2.add(lblLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 300, 90));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("CORREO");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 90, 60));

        jTextField2.setBackground(new java.awt.Color(227, 251, 230));
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 196, 76), 2));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 340, 60));

        jTextField3.setBackground(new java.awt.Color(227, 251, 230));
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 196, 76), 2));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 340, 60));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("ID");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 90, 60));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("NOMBRE");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 90, 60));

        javax.swing.GroupLayout frmCrearCuentaLayout = new javax.swing.GroupLayout(frmCrearCuenta.getContentPane());
        frmCrearCuenta.getContentPane().setLayout(frmCrearCuentaLayout);
        frmCrearCuentaLayout.setHorizontalGroup(
            frmCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(frmCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frmCrearCuentaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        frmCrearCuentaLayout.setVerticalGroup(
            frmCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(frmCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frmCrearCuentaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setFocusCycleRoot(false);
        setFocusTraversalPolicyProvider(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Logo.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 300, 90));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("TITULO");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 400, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setText("Cantidad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 150, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setText("Valor (c/u)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 150, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Subtotal");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 150, 30));

        lbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl.setForeground(new java.awt.Color(1, 196, 76));
        lbl.setText("Cliente");
        jPanel1.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, 40));

        lblCliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 170, 40));

        lblCantidad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 240, 30));

        lblValorUnidad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblValorUnidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblValorUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 240, 30));

        lblDescuento.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDescuento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 170, 30));

        jScrollPane1.setBorder(null);
        jScrollPane1.setEnabled(false);
        jScrollPane1.setFocusable(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setRequestFocusEnabled(false);
        jScrollPane1.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setWheelScrollingEnabled(false);

        txADescripcion.setEditable(false);
        txADescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txADescripcion.setColumns(8);
        txADescripcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txADescripcion.setLineWrap(true);
        txADescripcion.setRows(8);
        txADescripcion.setWrapStyleWord(true);
        txADescripcion.setBorder(null);
        txADescripcion.setFocusable(false);
        txADescripcion.setRequestFocusEnabled(false);
        txADescripcion.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(txADescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 420, 110));

        Subtotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Subtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Subtotal.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel1.add(Subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 170, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Linea.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 420, 30));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(1, 196, 76));
        jLabel13.setText("TOTAL");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 140, -1));

        btnCancelar.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(153, 153, 153));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setDefaultCapable(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setRequestFocusEnabled(false);
        btnCancelar.setVerifyInputWhenFocusTarget(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 130, 50));

        btnPagar.setBackground(new java.awt.Color(1, 196, 76));
        btnPagar.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnPagar.setText("Pagar");
        btnPagar.setBorder(null);
        btnPagar.setContentAreaFilled(false);
        btnPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPagar.setFocusPainted(false);
        btnPagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPagar.setOpaque(true);
        btnPagar.setRequestFocusEnabled(false);
        btnPagar.setVerifyInputWhenFocusTarget(false);
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 130, 50));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("$");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 40, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Descuento");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 150, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel8.setText("Descripción");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 150, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 196, 76));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("$");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 40, 30));

        lblTotal.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(1, 196, 76));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 170, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("$");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        if (btnPagar.getText().equals("Pagar")) {
            Zoopolis.setValidarAccion(false);
            Index.iniciarSesion();
            if (Zoopolis.getUsuarioActual() != null) {
                cambiarBoton();
            } 
        }else {
                registrarVenta();
                JOptionPane.showMessageDialog(null, "SU COMPRAR SE REALIZO SATISFACTORIAMENTE", "EXISTOSA", JOptionPane.OK_OPTION);
                dispose();
            }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void registrarVenta() {
        Zoopolis.getUsuarioActual().addVenta(ventaLocal);
        Zoopolis.deshabiliarUsuario();
    }

    private void cambiarBoton() {
        btnPagar.setText("Confirmar");
        lblCliente.setText(Zoopolis.getUsuarioActual().getNombre());
        crearObjetos();
        lblTotal.setText("" + ventaLocal.getTotal());
        lblDescuento.setText("" + ventaLocal.getDescontado());      // OJO, FALTA PONERLE TAMBIEN EL PORCENTAJE A LA VISTA Y SUBTOTAL
    }

    private void crearObjetos() {
        Ticket ticket = new Ticket(Double.parseDouble(lblValorUnidad.getText()), txADescripcion.getText(), lblTitulo.getText());
        ventaLocal = new Venta(lblCliente.getText(), Integer.parseInt(lblCantidad.getText()), ticket);
        Zoopolis.getUsuarioActual().contarVisitas();
        if (Zoopolis.getUsuarioActual().getVisitas() % 5 == 0) {
            ventaLocal.descontar(10);
        }else{
            ventaLocal.descontar(0);
        } 
    }

    public static void crearCuenta() {
        CrearCuenta cc = new CrearCuenta(frmCrearCuenta, true);
        cc.setVisible(true);
    }

    public static JFrame getFrmCrear() {
        return frmCrearCuenta;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Compra dialog = new Compra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Subtotal;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnInicioDeSesion;
    private javax.swing.JButton btnPagar;
    private static javax.swing.JFrame frmCrearCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblValorUnidad;
    private javax.swing.JTextArea txADescripcion;
    // End of variables declaration//GEN-END:variables
}
