/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.zoopolis.view;

/**
 *
 * @author Joseph Roldan, Carlos Castaño, Osvairo Moreno
 */
public class IndexAdmin extends javax.swing.JFrame {

    /**
     * Creates new form InicioAdmin
     */
    public IndexAdmin() {
        initComponents();
        btnInicio.setForeground(new java.awt.Color(1, 196, 76));
         btnInicio.setFont(new java.awt.Font("Arial", 1, 25));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblAventura = new javax.swing.JLabel();
        lblEsTiempo = new javax.swing.JLabel();
        lblPortada = new javax.swing.JLabel();
        lblFondoPortada = new javax.swing.JLabel();
        btnIrAnimal = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnAnimal = new javax.swing.JButton();
        btnRegistroAnimal = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnBalance = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Logo.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 300, 90));

        lblAventura.setFont(new java.awt.Font("Microsoft YaHei", 1, 82)); // NOI18N
        lblAventura.setForeground(new java.awt.Color(1, 196, 76));
        lblAventura.setText("ZOOPOLIS");
        jPanel1.add(lblAventura, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        lblEsTiempo.setFont(new java.awt.Font("Microsoft YaHei", 1, 48)); // NOI18N
        lblEsTiempo.setText("Portal Administrativo");
        jPanel1.add(lblEsTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        lblPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/PortadaAdmin.jpg"))); // NOI18N
        jPanel1.add(lblPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        lblFondoPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/FondoPortada.jpg"))); // NOI18N
        jPanel1.add(lblFondoPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        btnIrAnimal.setBackground(new java.awt.Color(1, 196, 76));
        btnIrAnimal.setFont(new java.awt.Font("Microsoft YaHei", 1, 25)); // NOI18N
        btnIrAnimal.setForeground(new java.awt.Color(255, 255, 255));
        btnIrAnimal.setText("ANIMALES");
        btnIrAnimal.setBorder(null);
        btnIrAnimal.setContentAreaFilled(false);
        btnIrAnimal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIrAnimal.setFocusPainted(false);
        btnIrAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIrAnimal.setOpaque(true);
        btnIrAnimal.setRequestFocusEnabled(false);
        btnIrAnimal.setVerifyInputWhenFocusTarget(false);
        btnIrAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrAnimalActionPerformed(evt);
            }
        });
        jPanel1.add(btnIrAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 265, 89));

        btnExit.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Exit.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setDefaultCapable(false);
        btnExit.setFocusPainted(false);
        btnExit.setFocusable(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 50, 50, 50));

        btnAnimal.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnAnimal.setText("Animales");
        btnAnimal.setBorder(null);
        btnAnimal.setBorderPainted(false);
        btnAnimal.setContentAreaFilled(false);
        btnAnimal.setDefaultCapable(false);
        btnAnimal.setFocusPainted(false);
        btnAnimal.setFocusable(false);
        btnAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimalActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 130, 50));

        btnRegistroAnimal.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnRegistroAnimal.setText("Registro Animal");
        btnRegistroAnimal.setBorder(null);
        btnRegistroAnimal.setBorderPainted(false);
        btnRegistroAnimal.setContentAreaFilled(false);
        btnRegistroAnimal.setDefaultCapable(false);
        btnRegistroAnimal.setFocusPainted(false);
        btnRegistroAnimal.setFocusable(false);
        btnRegistroAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAnimalActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistroAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 210, 50));

        btnInicio.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setBorder(null);
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setDefaultCapable(false);
        btnInicio.setFocusPainted(false);
        btnInicio.setFocusable(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 100, 50));

        btnBalance.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnBalance.setText("Balance");
        btnBalance.setBorder(null);
        btnBalance.setBorderPainted(false);
        btnBalance.setContentAreaFilled(false);
        btnBalance.setDefaultCapable(false);
        btnBalance.setFocusPainted(false);
        btnBalance.setFocusable(false);
        btnBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceActionPerformed(evt);
            }
        });
        jPanel1.add(btnBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIrAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrAnimalActionPerformed
        irAnimales();
        dispose();
    }//GEN-LAST:event_btnIrAnimalActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        exit();
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimalActionPerformed
        irAnimales();
        dispose();
    }//GEN-LAST:event_btnAnimalActionPerformed

    private void btnRegistroAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAnimalActionPerformed
        irRegsitroAnimal();
        dispose();
    }//GEN-LAST:event_btnRegistroAnimalActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceActionPerformed
        irBalance();
        dispose();
    }//GEN-LAST:event_btnBalanceActionPerformed

    public static void irAnimales() {
        Animales animales = new Animales();
        animales.setVisible(true);
    }

    public static void irRegsitroAnimal() {
        RegistroAnimal ra = new RegistroAnimal();
        ra.setVisible(true);

    }

    public static void irBalance() {
        Balance balance = new Balance();
        balance.setVisible(true);

    }

    public static void exit() {
        Index cerrar = new Index();
        cerrar.setVisible(true);
    }
    
    public static void irInicio() {
        IndexAdmin inicio = new IndexAdmin();
        inicio.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndexAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnimal;
    private javax.swing.JButton btnBalance;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnIrAnimal;
    private javax.swing.JButton btnRegistroAnimal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAventura;
    private javax.swing.JLabel lblEsTiempo;
    private javax.swing.JLabel lblFondoPortada;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPortada;
    // End of variables declaration//GEN-END:variables
}
