/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.zoopolis.view;

import com.zoopolis.model.Zoopolis;
/**
 *
 * @author Joseph Roldan, Carlos Castaño, Osvairo Moreno
 */
public class Planes extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Planes() {
        initComponents();
        btnPlanes.setForeground(new java.awt.Color(1, 196, 76));
        btnPlanes.setFont(new java.awt.Font("Arial", 1, 25));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPlanes = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        bntInicio = new javax.swing.JButton();
        btnTicket = new javax.swing.JButton();
        btnPlanes = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnFelina = new javax.swing.JButton();
        lblFFelina = new javax.swing.JLabel();
        btnReptiliana = new javax.swing.JButton();
        lblFReptiliana = new javax.swing.JLabel();
        btnAcuatica = new javax.swing.JButton();
        lblFAcuatica = new javax.swing.JLabel();
        btnTropical = new javax.swing.JButton();
        lblFTropical = new javax.swing.JLabel();
        btnAnimalTotal = new javax.swing.JButton();
        lblFAnimalTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ZOOPOLIS - Planes");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panPlanes.setBackground(new java.awt.Color(255, 255, 255));
        panPlanes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Logo.png"))); // NOI18N
        panPlanes.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 300, 90));

        bntInicio.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        bntInicio.setText("Inicio");
        bntInicio.setBorder(null);
        bntInicio.setBorderPainted(false);
        bntInicio.setContentAreaFilled(false);
        bntInicio.setDefaultCapable(false);
        bntInicio.setFocusPainted(false);
        bntInicio.setFocusable(false);
        bntInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntInicioActionPerformed(evt);
            }
        });
        panPlanes.add(bntInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 100, 50));

        btnTicket.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnTicket.setText("Ticket");
        btnTicket.setBorder(null);
        btnTicket.setBorderPainted(false);
        btnTicket.setContentAreaFilled(false);
        btnTicket.setDefaultCapable(false);
        btnTicket.setFocusPainted(false);
        btnTicket.setFocusable(false);
        btnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketActionPerformed(evt);
            }
        });
        panPlanes.add(btnTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 100, 50));

        btnPlanes.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnPlanes.setText("Planes");
        btnPlanes.setBorder(null);
        btnPlanes.setBorderPainted(false);
        btnPlanes.setContentAreaFilled(false);
        btnPlanes.setDefaultCapable(false);
        btnPlanes.setFocusPainted(false);
        btnPlanes.setFocusable(false);
        panPlanes.add(btnPlanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 100, 50));

        btnAdmin.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnAdmin.setText("Admin");
        btnAdmin.setBorder(null);
        btnAdmin.setBorderPainted(false);
        btnAdmin.setContentAreaFilled(false);
        btnAdmin.setDefaultCapable(false);
        btnAdmin.setFocusPainted(false);
        btnAdmin.setFocusable(false);
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        panPlanes.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 100, 50));

        btnFelina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Aventura Felina.png"))); // NOI18N
        btnFelina.setBorder(null);
        btnFelina.setBorderPainted(false);
        btnFelina.setContentAreaFilled(false);
        btnFelina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFelina.setFocusPainted(false);
        btnFelina.setFocusable(false);
        btnFelina.setRequestFocusEnabled(false);
        btnFelina.setRolloverEnabled(false);
        btnFelina.setVerifyInputWhenFocusTarget(false);
        btnFelina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFelinaActionPerformed(evt);
            }
        });
        panPlanes.add(btnFelina, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 470, 184));

        lblFFelina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/AmarilloFondo.jpg"))); // NOI18N
        panPlanes.add(lblFFelina, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 470, 184));

        btnReptiliana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Aventura Reptiliana.png"))); // NOI18N
        btnReptiliana.setBorder(null);
        btnReptiliana.setBorderPainted(false);
        btnReptiliana.setContentAreaFilled(false);
        btnReptiliana.setDefaultCapable(false);
        btnReptiliana.setFocusPainted(false);
        btnReptiliana.setFocusable(false);
        btnReptiliana.setRequestFocusEnabled(false);
        btnReptiliana.setRolloverEnabled(false);
        btnReptiliana.setVerifyInputWhenFocusTarget(false);
        btnReptiliana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReptilianaActionPerformed(evt);
            }
        });
        panPlanes.add(btnReptiliana, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 470, 184));

        lblFReptiliana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/VerdeFondo.jpg"))); // NOI18N
        panPlanes.add(lblFReptiliana, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 470, 184));

        btnAcuatica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Aventura Acuatica.png"))); // NOI18N
        btnAcuatica.setBorder(null);
        btnAcuatica.setBorderPainted(false);
        btnAcuatica.setContentAreaFilled(false);
        btnAcuatica.setDefaultCapable(false);
        btnAcuatica.setFocusPainted(false);
        btnAcuatica.setFocusable(false);
        btnAcuatica.setRequestFocusEnabled(false);
        btnAcuatica.setRolloverEnabled(false);
        btnAcuatica.setVerifyInputWhenFocusTarget(false);
        btnAcuatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcuaticaActionPerformed(evt);
            }
        });
        panPlanes.add(btnAcuatica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 304, 319));

        lblFAcuatica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/AzulFondo.jpg"))); // NOI18N
        panPlanes.add(lblFAcuatica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 304, 319));

        btnTropical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Aventura Tropical.png"))); // NOI18N
        btnTropical.setBorder(null);
        btnTropical.setBorderPainted(false);
        btnTropical.setContentAreaFilled(false);
        btnTropical.setDefaultCapable(false);
        btnTropical.setFocusPainted(false);
        btnTropical.setFocusable(false);
        btnTropical.setRequestFocusEnabled(false);
        btnTropical.setRolloverEnabled(false);
        btnTropical.setVerifyInputWhenFocusTarget(false);
        btnTropical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTropicalActionPerformed(evt);
            }
        });
        panPlanes.add(btnTropical, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 304, 319));

        lblFTropical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/VerdeClaroFondo.jpg"))); // NOI18N
        panPlanes.add(lblFTropical, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 304, 319));

        btnAnimalTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Aventura Animal Total.png"))); // NOI18N
        btnAnimalTotal.setBorder(null);
        btnAnimalTotal.setBorderPainted(false);
        btnAnimalTotal.setContentAreaFilled(false);
        btnAnimalTotal.setDefaultCapable(false);
        btnAnimalTotal.setFocusPainted(false);
        btnAnimalTotal.setFocusable(false);
        btnAnimalTotal.setRequestFocusEnabled(false);
        btnAnimalTotal.setRolloverEnabled(false);
        btnAnimalTotal.setVerifyInputWhenFocusTarget(false);
        btnAnimalTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimalTotalActionPerformed(evt);
            }
        });
        panPlanes.add(btnAnimalTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 304, 319));

        lblFAnimalTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/RojoFondo.jpg"))); // NOI18N
        panPlanes.add(lblFAnimalTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 304, 319));

        getContentPane().add(panPlanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bntInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntInicioActionPerformed
        Index.irInicio();
        dispose();
    }//GEN-LAST:event_bntInicioActionPerformed

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        Index.irTicket();
        dispose();
    }//GEN-LAST:event_btnTicketActionPerformed

    private void btnFelinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFelinaActionPerformed
        Index.irTicket('1');
        dispose();
    }//GEN-LAST:event_btnFelinaActionPerformed

    private void btnAcuaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcuaticaActionPerformed
        Index.irTicket('3');
        dispose();
    }//GEN-LAST:event_btnAcuaticaActionPerformed

    private void btnTropicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTropicalActionPerformed
        Index.irTicket('4');
        dispose();
    }//GEN-LAST:event_btnTropicalActionPerformed

    private void btnAnimalTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimalTotalActionPerformed
        Index.irTicket('5');
        dispose();
    }//GEN-LAST:event_btnAnimalTotalActionPerformed

    private void btnReptilianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReptilianaActionPerformed
        Index.irTicket('2');
        dispose();
    }//GEN-LAST:event_btnReptilianaActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        Zoopolis.setValidarAccion(true);
        Index.iniciarSesion();
        if(Zoopolis.getAdminValido()){
             dispose();
         }
    }//GEN-LAST:event_btnAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Planes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Planes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Planes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Planes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Planes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntInicio;
    private javax.swing.JButton btnAcuatica;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnAnimalTotal;
    private javax.swing.JButton btnFelina;
    private javax.swing.JButton btnPlanes;
    private javax.swing.JButton btnReptiliana;
    private javax.swing.JButton btnTicket;
    private javax.swing.JButton btnTropical;
    private javax.swing.JLabel lblFAcuatica;
    private javax.swing.JLabel lblFAnimalTotal;
    private javax.swing.JLabel lblFFelina;
    private javax.swing.JLabel lblFReptiliana;
    private javax.swing.JLabel lblFTropical;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel panPlanes;
    // End of variables declaration//GEN-END:variables
}
