/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.zoopolis.view;

import com.zoopolis.model.AnimalDomestico;
import com.zoopolis.model.AnimalSalvaje;
import com.zoopolis.model.Zoopolis;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Joseph Roldan, Carlos Castaño, Osvairo Moreno
 */
public class RegistroAnimal extends javax.swing.JFrame {

    /**
     * Creates new form RegsitroAnimal
     */
    public RegistroAnimal() {
        initComponents();
        btnRegistroAnimal.setForeground(new java.awt.Color(1, 196, 76));
         btnRegistroAnimal.setFont(new java.awt.Font("Arial", 1, 25));
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        btngTipoAnimal = new javax.swing.ButtonGroup();
        btngSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        rbtnAnimalDomestico = new javax.swing.JRadioButton();
        rbtnAnimalSalvaje = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEspecie = new javax.swing.JTextField();
        btnExaminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        txtRaza = new javax.swing.JTextField();
        txtHabitat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txADescripcion = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnRegistroAnimal = new javax.swing.JButton();
        btnAnimal = new javax.swing.JButton();
        btnBalance = new javax.swing.JButton();
        btnExit1 = new javax.swing.JButton();
        cmbPeligrosidad = new javax.swing.JComboBox<>();
        rbnMacho = new javax.swing.JRadioButton();
        rbnHembra = new javax.swing.JRadioButton();
        spnEdad = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Logo.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 300, 90));

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Foto.png"))); // NOI18N
        lblFoto.setOpaque(true);
        jPanel1.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 320, 190));

        btngTipoAnimal.add(rbtnAnimalDomestico);
        rbtnAnimalDomestico.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        rbtnAnimalDomestico.setText("Animal Domestico");
        rbtnAnimalDomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAnimalDomesticoActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnAnimalDomestico, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        btngTipoAnimal.add(rbtnAnimalSalvaje);
        rbtnAnimalSalvaje.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        rbtnAnimalSalvaje.setText("Animal Salvaje");
        rbtnAnimalSalvaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAnimalSalvajeActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnAnimalSalvaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, -1, -1));

        jLabel2.setBackground(new java.awt.Color(1, 196, 76));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 460, 45));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel4.setText("Especie");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, 50));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel5.setText("Sexo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, 50));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel6.setText("Edad");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, 50));

        txtEspecie.setBackground(new java.awt.Color(227, 251, 230));
        txtEspecie.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtEspecie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 196, 76), 2));
        jPanel1.add(txtEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 280, 35));

        btnExaminar.setBackground(new java.awt.Color(1, 196, 76));
        btnExaminar.setFont(new java.awt.Font("Microsoft YaHei", 0, 20)); // NOI18N
        btnExaminar.setForeground(new java.awt.Color(255, 255, 255));
        btnExaminar.setText("Examinar");
        btnExaminar.setBorder(null);
        btnExaminar.setContentAreaFilled(false);
        btnExaminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExaminar.setFocusPainted(false);
        btnExaminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExaminar.setOpaque(true);
        btnExaminar.setRequestFocusEnabled(false);
        btnExaminar.setVerifyInputWhenFocusTarget(false);
        btnExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnExaminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 320, 40));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Linea_1.png"))); // NOI18N
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 912, 50));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(1, 196, 76));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DATOS ESPECIFICOS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 340, 40));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel9.setText("Raza");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, 50));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel10.setText("Descripción");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 150, 30));

        txtColor.setBackground(new java.awt.Color(227, 251, 230));
        txtColor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 196, 76), 2));
        jPanel1.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 280, 35));

        txtRaza.setBackground(new java.awt.Color(227, 251, 230));
        txtRaza.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtRaza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 196, 76), 2));
        txtRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazaActionPerformed(evt);
            }
        });
        jPanel1.add(txtRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 280, 35));

        txtHabitat.setBackground(new java.awt.Color(227, 251, 230));
        txtHabitat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtHabitat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 196, 76), 2));
        jPanel1.add(txtHabitat, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 280, 35));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel11.setText("Peligrosidad");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, 50));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel12.setText("Habitat");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, 50));

        btnCerrar.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(153, 153, 153));
        btnCerrar.setText("Cancelar");
        btnCerrar.setBorder(null);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setDefaultCapable(false);
        btnCerrar.setFocusPainted(false);
        btnCerrar.setFocusable(false);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setRequestFocusEnabled(false);
        btnCerrar.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 610, 180, 50));

        btnRegistrar.setBackground(new java.awt.Color(1, 196, 76));
        btnRegistrar.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(null);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setOpaque(true);
        btnRegistrar.setRequestFocusEnabled(false);
        btnRegistrar.setVerifyInputWhenFocusTarget(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 610, 180, 50));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 196, 76), 2));

        txADescripcion.setColumns(20);
        txADescripcion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txADescripcion.setLineWrap(true);
        txADescripcion.setRows(5);
        txADescripcion.setWrapStyleWord(true);
        txADescripcion.setBorder(null);
        jScrollPane1.setViewportView(txADescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 400, 80));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel13.setText("Color");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, 50));

        btnInicio.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setBorder(null);
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setDefaultCapable(false);
        btnInicio.setFocusPainted(false);
        btnInicio.setFocusable(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 100, 50));

        btnRegistroAnimal.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnRegistroAnimal.setText("Registro Animal");
        btnRegistroAnimal.setBorder(null);
        btnRegistroAnimal.setBorderPainted(false);
        btnRegistroAnimal.setContentAreaFilled(false);
        btnRegistroAnimal.setDefaultCapable(false);
        btnRegistroAnimal.setFocusPainted(false);
        btnRegistroAnimal.setFocusable(false);
        btnRegistroAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAnimalActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistroAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 210, 50));

        btnAnimal.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnAnimal.setText("Animales");
        btnAnimal.setBorder(null);
        btnAnimal.setBorderPainted(false);
        btnAnimal.setContentAreaFilled(false);
        btnAnimal.setDefaultCapable(false);
        btnAnimal.setFocusPainted(false);
        btnAnimal.setFocusable(false);
        btnAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimalActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 130, 50));

        btnBalance.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnBalance.setText("Balance");
        btnBalance.setBorder(null);
        btnBalance.setBorderPainted(false);
        btnBalance.setContentAreaFilled(false);
        btnBalance.setDefaultCapable(false);
        btnBalance.setFocusPainted(false);
        btnBalance.setFocusable(false);
        btnBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceActionPerformed(evt);
            }
        });
        jPanel1.add(btnBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 120, 50));

        btnExit1.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Exit.png"))); // NOI18N
        btnExit1.setBorder(null);
        btnExit1.setBorderPainted(false);
        btnExit1.setContentAreaFilled(false);
        btnExit1.setDefaultCapable(false);
        btnExit1.setFocusPainted(false);
        btnExit1.setFocusable(false);
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 50, 50, 50));

        cmbPeligrosidad.setBackground(new java.awt.Color(227, 251, 230));
        cmbPeligrosidad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbPeligrosidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar...", "Muy alto", "Alto", "Medio", "Bajo", "Muy bajo" }));
        cmbPeligrosidad.setBorder(null);
        cmbPeligrosidad.setOpaque(true);
        cmbPeligrosidad.setRequestFocusEnabled(false);
        cmbPeligrosidad.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(cmbPeligrosidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, 280, 30));

        btngSexo.add(rbnMacho);
        rbnMacho.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbnMacho.setText("Macho");
        jPanel1.add(rbnMacho, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        btngSexo.add(rbnHembra);
        rbnHembra.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbnHembra.setText("Hembra");
        jPanel1.add(rbnHembra, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, -1, -1));

        spnEdad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        spnEdad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));
        spnEdad.setBorder(null);
        jPanel1.add(spnEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, -1, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarActionPerformed
        JFileChooser jf = new JFileChooser();
        jf.setMultiSelectionEnabled(false);
        int i = 0;
        if(jf.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            rsdragdropfiles.RSDragDropFiles.setCopiar(jf.getSelectedFile().toString(), "src/main/resources/assets/animal"+i);
            i++;
        }
    }//GEN-LAST:event_btnExaminarActionPerformed

    private void txtRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazaActionPerformed

    private void rbtnAnimalDomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAnimalDomesticoActionPerformed
        cmbPeligrosidad.setEnabled(false);
        txtHabitat.setEnabled(false);
        txtRaza.setEnabled(true);
        txtColor.setEnabled(true); 
    }//GEN-LAST:event_rbtnAnimalDomesticoActionPerformed

    private void rbtnAnimalSalvajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAnimalSalvajeActionPerformed
        txtRaza.setEnabled(false);
        txtColor.setEnabled(false);
        cmbPeligrosidad.setEnabled(true);
        txtHabitat.setEnabled(true);
    }//GEN-LAST:event_rbtnAnimalSalvajeActionPerformed

    private void btnRegistroAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAnimalActionPerformed

    }//GEN-LAST:event_btnRegistroAnimalActionPerformed

    private void btnAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimalActionPerformed
            IndexAdmin.irAnimales();
            dispose();
    }//GEN-LAST:event_btnAnimalActionPerformed

    private void btnBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceActionPerformed
            IndexAdmin.irBalance();
            dispose();
    }//GEN-LAST:event_btnBalanceActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        IndexAdmin.exit();
        dispose();
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        capturarDatos();
        limpiarCampos();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        IndexAdmin.irInicio();
        dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void capturarDatos(){
       if(rbtnAnimalDomestico.isSelected()== true){
           AnimalDomestico ad = new AnimalDomestico(txtRaza.getText(), txtColor.getText(),"IMAGEN BONITA", txtEspecie.getText(), btngSexo.getSelection().toString(), Integer.parseInt(spnEdad.getValue().toString()), txADescripcion.getText());
           Zoopolis.animalesDomestico.add(ad);
           JOptionPane.showMessageDialog(null, "SE REGISTRO EL ANIMAL DOMESTICO", "EXISTOSA", JOptionPane.OK_OPTION);
        }else{
           AnimalSalvaje as = new AnimalSalvaje(cmbPeligrosidad.getSelectedItem().toString(), "IMAGEN RUDA", txtEspecie.getText(), btngSexo.getSelection().toString(), Integer.parseInt(spnEdad.getValue().toString()), txADescripcion.getText(), txtHabitat.getText()); 
           Zoopolis.animalesSalvaje.add(as);
           JOptionPane.showMessageDialog(null, "SE REGISTRO EL ANIMAL DOMESTICO", "EXISTOSA", JOptionPane.OK_OPTION);
       }
       
    }
    
    public void limpiarCampos(){
        rbtnAnimalDomestico.setSelected(false);
        rbtnAnimalSalvaje.setSelected(false);
        txtEspecie.setText("");
        btngSexo.clearSelection();
        spnEdad.setValue(0);
        txtRaza.setText("");
        txtColor.setText("");
        txtHabitat.setText("");
        cmbPeligrosidad.setSelectedIndex(0);
        txADescripcion.setText("");
        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Foto.png")));
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnimal;
    private javax.swing.JButton btnBalance;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnExaminar;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistroAnimal;
    private javax.swing.ButtonGroup btngSexo;
    private javax.swing.ButtonGroup btngTipoAnimal;
    private javax.swing.JComboBox<String> cmbPeligrosidad;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JRadioButton rbnHembra;
    private javax.swing.JRadioButton rbnMacho;
    private javax.swing.JRadioButton rbtnAnimalDomestico;
    private javax.swing.JRadioButton rbtnAnimalSalvaje;
    private javax.swing.JSpinner spnEdad;
    private javax.swing.JTextArea txADescripcion;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtHabitat;
    private javax.swing.JTextField txtRaza;
    // End of variables declaration//GEN-END:variables
}
