/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.zoopolis.interfaz;

import com.zoopolis.zoopolis.Zoopolis;

/**
 *
 * @author Joseph Roldan, Carlos Castaño, Osvairo Moreno 
 * @version 2.0
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        btnInicio.setForeground(new java.awt.Color(1, 196, 76));
        btnInicio.setFont(new java.awt.Font("Arial", 1, 25));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmInicioSesion = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        btnCrearCuenta1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        lblLogo1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panInicio = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnGoPlan = new javax.swing.JButton();
        lblAventura = new javax.swing.JLabel();
        lblEsTiempo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblPortada = new javax.swing.JLabel();
        lblFondoPortada = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnTicket = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnPlanes = new javax.swing.JButton();

        frmInicioSesion.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frmInicioSesion.setAutoRequestFocus(false);
        frmInicioSesion.setFocusCycleRoot(false);
        frmInicioSesion.setResizable(false);
        frmInicioSesion.setSize(new java.awt.Dimension(650, 550));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(650, 550));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrearCuenta1.setBackground(new java.awt.Color(1, 196, 76));
        btnCrearCuenta1.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnCrearCuenta1.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCuenta1.setText("INICIAR SESION");
        btnCrearCuenta1.setBorder(null);
        btnCrearCuenta1.setContentAreaFilled(false);
        btnCrearCuenta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearCuenta1.setFocusPainted(false);
        btnCrearCuenta1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCrearCuenta1.setOpaque(true);
        btnCrearCuenta1.setRequestFocusEnabled(false);
        btnCrearCuenta1.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnCrearCuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 180, 50));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INICIAR SESION");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 300, -1));

        btnIniciarSesion.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(153, 153, 153));
        btnIniciarSesion.setText("Crear cuenta");
        btnIniciarSesion.setBorder(null);
        btnIniciarSesion.setBorderPainted(false);
        btnIniciarSesion.setContentAreaFilled(false);
        btnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarSesion.setDefaultCapable(false);
        btnIniciarSesion.setFocusPainted(false);
        btnIniciarSesion.setFocusable(false);
        btnIniciarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIniciarSesion.setRequestFocusEnabled(false);
        btnIniciarSesion.setVerifyInputWhenFocusTarget(false);
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 180, 50));

        jTextField1.setBackground(new java.awt.Color(227, 251, 230));
        jTextField1.setBorder(null);
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 300, 60));

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Logo.png"))); // NOI18N
        jPanel2.add(lblLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 300, 90));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Contraseña (ID)");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 300, -1));

        frmInicioSesion.getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ZOOPOLIS");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panInicio.setBackground(new java.awt.Color(255, 255, 255));
        panInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Arial", 2, 17)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(153, 153, 153));
        jTextPane1.setText("Con mas de 2500 animales repartidos en 2000 hectarias\ny con aventura  en cada rincon te los pasara increible\n                            en ZOOPOLIS");
        jTextPane1.setAutoscrolls(false);
        jTextPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextPane1.setFocusCycleRoot(false);
        jTextPane1.setFocusable(false);
        jTextPane1.setRequestFocusEnabled(false);
        jTextPane1.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(jTextPane1);

        panInicio.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 440, 80));

        btnGoPlan.setBackground(new java.awt.Color(1, 196, 76));
        btnGoPlan.setFont(new java.awt.Font("Microsoft YaHei", 1, 25)); // NOI18N
        btnGoPlan.setForeground(new java.awt.Color(255, 255, 255));
        btnGoPlan.setText("COMPRAR PLAN");
        btnGoPlan.setBorder(null);
        btnGoPlan.setContentAreaFilled(false);
        btnGoPlan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoPlan.setFocusPainted(false);
        btnGoPlan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoPlan.setOpaque(true);
        btnGoPlan.setRequestFocusEnabled(false);
        btnGoPlan.setVerifyInputWhenFocusTarget(false);
        btnGoPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoPlanActionPerformed(evt);
            }
        });
        panInicio.add(btnGoPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 265, 89));

        lblAventura.setFont(new java.awt.Font("Microsoft YaHei", 1, 82)); // NOI18N
        lblAventura.setForeground(new java.awt.Color(1, 196, 76));
        lblAventura.setText("AVENTURA");
        panInicio.add(lblAventura, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        lblEsTiempo.setFont(new java.awt.Font("Microsoft YaHei", 1, 70)); // NOI18N
        lblEsTiempo.setText("Es tiempo de");
        panInicio.add(lblEsTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Logo.png"))); // NOI18N
        panInicio.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 300, 90));

        lblPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Portada.jpg"))); // NOI18N
        panInicio.add(lblPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        lblFondoPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/FondoPortada.jpg"))); // NOI18N
        panInicio.add(lblFondoPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        btnInicio.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setBorder(null);
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setDefaultCapable(false);
        btnInicio.setFocusPainted(false);
        btnInicio.setFocusable(false);
        panInicio.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 100, 50));

        btnTicket.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnTicket.setText("Ticket");
        btnTicket.setBorder(null);
        btnTicket.setBorderPainted(false);
        btnTicket.setContentAreaFilled(false);
        btnTicket.setDefaultCapable(false);
        btnTicket.setFocusPainted(false);
        btnTicket.setFocusable(false);
        btnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketActionPerformed(evt);
            }
        });
        panInicio.add(btnTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 100, 50));

        btnAdmin.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnAdmin.setText("Admin");
        btnAdmin.setBorder(null);
        btnAdmin.setBorderPainted(false);
        btnAdmin.setContentAreaFilled(false);
        btnAdmin.setDefaultCapable(false);
        btnAdmin.setFocusPainted(false);
        btnAdmin.setFocusable(false);
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        panInicio.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 100, 50));

        btnPlanes.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnPlanes.setText("Planes");
        btnPlanes.setBorder(null);
        btnPlanes.setBorderPainted(false);
        btnPlanes.setContentAreaFilled(false);
        btnPlanes.setDefaultCapable(false);
        btnPlanes.setFocusPainted(false);
        btnPlanes.setFocusable(false);
        btnPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanesActionPerformed(evt);
            }
        });
        panInicio.add(btnPlanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 100, 50));

        getContentPane().add(panInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        irTicket();
        dispose();
    }//GEN-LAST:event_btnTicketActionPerformed

    private void btnGoPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoPlanActionPerformed
        irPlanes();
        dispose();
    }//GEN-LAST:event_btnGoPlanActionPerformed

    private void btnPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanesActionPerformed
        irPlanes();
        dispose();
    }//GEN-LAST:event_btnPlanesActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
         iniciarSesion();
         frmInicioSesion.dispose();
         if(Zoopolis.getAdminValido()){
             dispose();
         }
         
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    public static void irPlanes() {
        Planes jfPlanes = new Planes();
        jfPlanes.setVisible(true);
    }

    public static void irInicio() {
        Index jfIndex = new Index();
        jfIndex.setVisible(true);
    }

    public static void irTicket() {
        Ticket jfTicket = new Ticket();
        jfTicket.setVisible(true);
    }

    public static void irTicket(char n) {
        Ticket jfTicket = new Ticket();
        jfTicket.setVisible(true);
        jfTicket.cambiarApariencia(n);
    }
    
    public static void iniciarSesion(){
       InicioSesion sesion = new InicioSesion(frmInicioSesion, true);
       sesion.setVisible(true);
       
    }
    
    
    
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnCrearCuenta1;
    private javax.swing.JButton btnGoPlan;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnPlanes;
    private javax.swing.JButton btnTicket;
    private static javax.swing.JFrame frmInicioSesion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblAventura;
    private javax.swing.JLabel lblEsTiempo;
    private javax.swing.JLabel lblFondoPortada;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblPortada;
    private javax.swing.JPanel panInicio;
    // End of variables declaration//GEN-END:variables
}
