/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.zoopolis.interfaz;

/**
 *
 * @author Joseph Roldan, Carlos Castaño, Osvairo Moreno
 */
public class IndexAdmin extends javax.swing.JFrame {

    /**
     * Creates new form InicioAdmin
     */
    public IndexAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnRegistroAnimal = new javax.swing.JButton();
        btnPlanes = new javax.swing.JButton();
        btnBalance = new javax.swing.JButton();
        lblAventura = new javax.swing.JLabel();
        lblEsTiempo = new javax.swing.JLabel();
        lblPortada = new javax.swing.JLabel();
        lblFondoPortada = new javax.swing.JLabel();
        btnGoPlan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Logo.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 300, 90));

        btnInicio.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setBorder(null);
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setDefaultCapable(false);
        btnInicio.setFocusPainted(false);
        btnInicio.setFocusable(false);
        jPanel1.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 100, 50));

        btnRegistroAnimal.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnRegistroAnimal.setText("Registro Animal");
        btnRegistroAnimal.setBorder(null);
        btnRegistroAnimal.setBorderPainted(false);
        btnRegistroAnimal.setContentAreaFilled(false);
        btnRegistroAnimal.setDefaultCapable(false);
        btnRegistroAnimal.setFocusPainted(false);
        btnRegistroAnimal.setFocusable(false);
        btnRegistroAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAnimalActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistroAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 210, 50));

        btnPlanes.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnPlanes.setText("Animales");
        btnPlanes.setBorder(null);
        btnPlanes.setBorderPainted(false);
        btnPlanes.setContentAreaFilled(false);
        btnPlanes.setDefaultCapable(false);
        btnPlanes.setFocusPainted(false);
        btnPlanes.setFocusable(false);
        btnPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanesActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 130, 50));

        btnBalance.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        btnBalance.setText("Balance");
        btnBalance.setBorder(null);
        btnBalance.setBorderPainted(false);
        btnBalance.setContentAreaFilled(false);
        btnBalance.setDefaultCapable(false);
        btnBalance.setFocusPainted(false);
        btnBalance.setFocusable(false);
        btnBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceActionPerformed(evt);
            }
        });
        jPanel1.add(btnBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 120, 50));

        lblAventura.setFont(new java.awt.Font("Microsoft YaHei", 1, 82)); // NOI18N
        lblAventura.setForeground(new java.awt.Color(1, 196, 76));
        lblAventura.setText("ZOOPOLIS");
        jPanel1.add(lblAventura, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        lblEsTiempo.setFont(new java.awt.Font("Microsoft YaHei", 1, 48)); // NOI18N
        lblEsTiempo.setText("Portal Administrativo");
        jPanel1.add(lblEsTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        lblPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/PortadaAdmin.jpg"))); // NOI18N
        jPanel1.add(lblPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        lblFondoPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/FondoPortada.jpg"))); // NOI18N
        jPanel1.add(lblFondoPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        btnGoPlan.setBackground(new java.awt.Color(1, 196, 76));
        btnGoPlan.setFont(new java.awt.Font("Microsoft YaHei", 1, 25)); // NOI18N
        btnGoPlan.setForeground(new java.awt.Color(255, 255, 255));
        btnGoPlan.setText("ANIMALES");
        btnGoPlan.setBorder(null);
        btnGoPlan.setContentAreaFilled(false);
        btnGoPlan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoPlan.setFocusPainted(false);
        btnGoPlan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoPlan.setOpaque(true);
        btnGoPlan.setRequestFocusEnabled(false);
        btnGoPlan.setVerifyInputWhenFocusTarget(false);
        btnGoPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoPlanActionPerformed(evt);
            }
        });
        jPanel1.add(btnGoPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 265, 89));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAnimalActionPerformed

    }//GEN-LAST:event_btnRegistroAnimalActionPerformed

    private void btnPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanesActionPerformed

    }//GEN-LAST:event_btnPlanesActionPerformed

    private void btnBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceActionPerformed

    }//GEN-LAST:event_btnBalanceActionPerformed

    private void btnGoPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoPlanActionPerformed
     
    }//GEN-LAST:event_btnGoPlanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndexAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBalance;
    private javax.swing.JButton btnGoPlan;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnPlanes;
    private javax.swing.JButton btnRegistroAnimal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAventura;
    private javax.swing.JLabel lblEsTiempo;
    private javax.swing.JLabel lblFondoPortada;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPortada;
    // End of variables declaration//GEN-END:variables
}
